-- MysticalAgriculture Automation Configuration
-- This file is auto-generated by the setup wizard
-- You can manually edit it if needed

return {
    -- Monitor for display (auto-detected)
    monitor = "monitor_0",
    
    -- ME Bridge from Advanced Peripherals
    meBridge = "meBridge_0",
    
    -- Central altar block
    altar = "inventory_0",
    
    -- 8 pedestals in clockwise order
    pedestals = {
        "inventory_1",
        "inventory_2", 
        "inventory_3",
        "inventory_4",
        "inventory_5",
        "inventory_6",
        "inventory_7",
        "inventory_8",
    },
    
    -- Redstone Integrator for altar activation
    redstoneIntegrator = "redstoneIntegrator_0",
    
    -- Which side of the integrator faces the altar
    redstoneSide = "north",
    
    -- Optional settings
    settings = {
        -- Time to wait for altar to complete (seconds)
        craftTimeout = 30,
        
        -- Update frequency for availability checks (seconds)
        updateInterval = 0.5,
        
        -- Colors
        colors = {
            available = colors.green,
            unavailable = colors.red,
            crafting = colors.yellow,
            background = colors.black,
            text = colors.white,
            header = colors.blue,
        }
    }
}